# Generated by Django 6.0.6 on 2026-06-04 21:27

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('edificio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edificios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'periodos_academicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.PositiveSmallIntegerField(default=3)),
                ('horas_semana', models.PositiveSmallIntegerField(default=4)),
                ('nivel_semestre', models.SmallIntegerField(blank=True, null=True)),
                ('electiva', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api.departamento')),
            ],
            options={
                'db_table': 'cursos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('docente_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo_maximo', models.CharField(blank=True, max_length=100, null=True)),
                ('dedicacion', models.CharField(blank=True, max_length=40, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='api.departamento')),
            ],
            options={
                'db_table': 'docentes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('aula_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='Salon de clase', max_length=60)),
                ('nombre', models.CharField(max_length=30)),
                ('piso', models.SmallIntegerField(blank=True, null=True)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(blank=True, db_column='edificio_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='api.edificio')),
            ],
            options={
                'db_table': 'aulas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoCurso',
            fields=[
                ('grupo_id', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(default='Presencial', max_length=30)),
                ('nombre_grupo', models.CharField(max_length=10)),
                ('cupo_maximo', models.PositiveSmallIntegerField(default=30)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='api.curso')),
                ('docente', models.ForeignKey(db_column='docente_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='api.docente')),
                ('periodo', models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='api.periodoacademico')),
            ],
            options={
                'db_table': 'grupos_curso',
                'ordering': ['periodo', 'curso', 'nombre_grupo'],
                'unique_together': {('curso', 'periodo', 'nombre_grupo')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_aplicacion', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='api.grupocurso')),
            ],
            options={
                'db_table': 'evaluaciones',
                'ordering': ['fecha_aplicacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=10)),
                ('numero_doc', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas',
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('tipo_doc', 'numero_doc')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='api.persona')),
            ],
            options={
                'db_table': 'estudiantes',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='api.persona'),
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('programa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nivel_formacion', models.CharField(max_length=60)),
                ('modalidad', models.CharField(default='Presencial', max_length=30)),
                ('creditos_totales', models.SmallIntegerField(blank=True, null=True)),
                ('duracion_semestres', models.SmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='api.departamento')),
            ],
            options={
                'db_table': 'programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api.programa'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario_id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.ForeignKey(db_column='aula_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.aula')),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.grupocurso')),
            ],
            options={
                'db_table': 'horarios',
                'ordering': ['dia', 'hora_inicio'],
                'unique_together': {('aula', 'dia', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='NotaEvaluacion',
            fields=[
                ('nota_id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ausente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='notas_evaluacion', to='api.estudiante')),
                ('evaluacion', models.ForeignKey(db_column='evaluacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api.evaluacion')),
            ],
            options={
                'db_table': 'notas_evaluacion',
                'ordering': ['-registrado_en'],
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('matricula_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Cancelada', 'Cancelada'), ('Retirada', 'Retirada'), ('Finalizada', 'Finalizada'), ('Pendiente pago', 'Pendiente pago')], default='Activa', max_length=30)),
                ('fecha_matricula', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.estudiante')),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.grupocurso')),
                ('periodo', models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.periodoacademico')),
            ],
            options={
                'db_table': 'matriculas',
                'ordering': ['-fecha_matricula'],
                'unique_together': {('estudiante', 'grupo')},
            },
        ),
    ]
